default_info: 
  port: 22
  username: root
  password: ~
  pkey_dir: /root/.ssh/id_rsa
  pre_cmd: ~
  waiting_jobs_dir: /userhome/cbh/EXP/21.10/_SSH_RUNNER/1_WAITING_JOBS
  sended_jobs_dir: /userhome/cbh/EXP/21.10/_SSH_RUNNER/2_SENDED_JOBS
  log_dir: /userhome/cbh/EXP/21.10/_SSH_RUNNER
  sleep: 300

machines_info:
# - ip: 10.35.199.170ww
#   name: 8-1
#   pre_cmd: 'export PATH=/opt/conda/bin:$PATH'
- ip: 10.162.109.215
  name: 16-1
  pre_cmd: 'export PATH=/opt/conda/bin:$PATH'



# - ip: 10.24.82.14
#   name: mac14
#   pre_cmd: 'export PATH=/home/cbh/anaconda3/envs/py38/bin:$PATH'
# - ip: 10.24.82.18
#   name: mac18
#   pre_cmd: 'export PATH=/home/cbh/miniconda3/envs/py38/bin:$PATH'
# - ip: 10.24.82.22
#   name: mac22
#   pre_cmd: 'export PATH=/home/cbh/anaconda3/envs/py38/bin:$PATH'

# - ip: 10.24.82.79
#   name: mac79
#   pre_cmd: 'export PATH=/home/cbh/anaconda3/envs/py38/bin:$PATH'